### ISSUE TITLE
oemof.solph; basic example error 

### ISSUE THREAD

**Issue by leyetunji** [oemof/oemof-solph#731]
Hi all, I'm trying to model a simple energy system to satisfy demand at least cost. I used the oemof solph basic example as a template, slightly modifying it to account for nuclear power source and peat CHP. After running the model on spyder I kept on getting value error. I'm sharing this to know where I got it wrong and how to fix the error? 

Below are the codes:
```python

from oemof.tools import logger
from oemof.tools import helpers

import oemof.solph as solph
import oemof.outputlib as outputlib

import logging
import os
import pandas as pd
import pprint as pp

try:
    import matplotlib.pyplot as plt
except ImportError:
    plt = None
    
solver = 'cbc'  # 'glpk', 'gurobi',....
debug = False  # Set number_of_timesteps to 3 to get a readable lp-file.
number_of_time_steps = 744
solver_verbose = False  # show/hide solver output

# initiate the logger (see the API docs for more information)
logger.define_logging(logfile='oemof_example.log',
                      screen_level=logging.INFO,
                      file_level=logging.DEBUG)

logging.info('Initialize the energy system')
date_time_index = pd.date_range('8/1/2020', periods=number_of_time_steps,
                                freq='H')

energysystem = solph.EnergySystem(timeindex=date_time_index)

# Read data file
filename = os.path.join(os.path.dirname(__file__), 'basic example.csv')
data = pd.read_csv(filename) 

##########################################################################
# Create oemof object
##########################################################################

logging.info('Create oemof objects')

# The bus objects were assigned to variables which makes it easier to connect
# components to these buses (see below).

# create peat bus
peat = solph.Bus(label="peat") 

# create electricity bus
bel = solph.Bus(label="electricity")

# create electricity bus
bth = solph.Bus(label="heat")

# adding the buses to the energy system
energysystem.add(peat, bel)

# create excess component for the electricity bus to allow overproduction
energysystem.add(solph.Sink(label='excess_bel', inputs={bel: solph.Flow()}))

# create source object representing peat commodity (annual limit)
energysystem.add(solph.Source(label='peat', outputs={peat: solph.Flow(
    nominal_value=29825293, summed_max=1)}))

# create nuclear bus
nuclear = solph.Bus(label="nuclear") 

# create nuclear electricity bus
beln = solph.Bus(label="nelectricity")

# adding the buses to the energy system
energysystem.add(nuclear, beln)

# create excess component for the electricity bus to allow overproduction
energysystem.add(solph.Sink(label='excess_bel', inputs={bel: solph.Flow()}))

# create source object representing uranuim commodity (annual limit)
energysystem.add(solph.Source(label='nuclear', outputs={nuclear: solph.Flow(
    nominal_value=29825293, summed_max=1)}))

# create fixed source object representing wind power plants
energysystem.add(solph.Source(label='wind', outputs={bel: solph.Flow(
    actual_value=data['wind'], nominal_value=1000000, fixed=True)}))

# create fixed source object representing pv power plants
energysystem.add(solph.Source(label='pv', outputs={bel: solph.Flow(
    actual_value=data['pv'], nominal_value=582000, fixed=True)}))

# create simple sink object representing the electrical demand
energysystem.add(solph.Sink(label='demand', inputs={bel: solph.Flow(
    actual_value=data['demand_el'], fixed=True, nominal_value=1)}))

# create fixed source object representing peat CHP power plants
energysystem.add(solph.Source(label='peat', inputs={bel: solph.Flow(
    actual_value=data['CHP'], nominal_value=29825293, summed_max=1)}))

# create simple transformer object representing a CHP plant
energysystem.add(solph.Transformer(
    label="peat",
    inputs={peat: solph.Flow()},
    outputs={bel: solph.Flow(nominal_value=10e10),
             bth: solph.Flow(nominal_value=10e10,variable_costs=50,
                             conversion_factors={bel: 0.58})}))
  
# create simple transformer object representing a Nuclear power plant
energysystem.add(solph.Transformer(
    label="nuclear",
    inputs={nuclear: solph.Flow()},
    outputs={beln: solph.Flow(nominal_value=10e10, variable_costs=50)},
    conversion_factors={bel: 0.36}))

# create storage object representing a battery
storage = solph.components.GenericStorage(
    nominal_storage_capacity=10077997,
    label='storage',
    inputs={bel: solph.Flow(nominal_value=10077997/6)},
    outputs={bel: solph.Flow(nominal_value=10077997/6, variable_costs=0.001)},
    loss_rate=0.00, initial_storage_level=None,
    inflow_conversion_factor=1, outflow_conversion_factor=0.8,
)

energysystem.add(storage)

##########################################################################
# Optimise the energy system and plot the results
##########################################################################

logging.info('Optimise the energy system')

# initialise the operational model
model = solph.Model(energysystem)

# This is for debugging only. It is not(!) necessary to solve the problem and
# should be set to False to save time and disc space in normal use. For
# debugging the timesteps should be set to 3, to increase the readability of
# the lp-file.

if debug:
    filename = os.path.join(
        helpers.extend_basic_path('lp_files'), 'basic_example.lp')
    logging.info('Store lp-file in {0}.'.format(filename))
    model.write(filename, io_options={'symbolic_solver_labels': True})
    
# if tee_switch is true solver messages will be displayed
logging.info('Solve the optimization problem')
model.solve(solver=solver, solve_kwargs={'tee': solver_verbose})

logging.info('Store the energy system with the results.')   

# The processing module of the outputlib can be used to extract the results
# from the model transfer them into a homogeneous structured dictionary.

# add results to the energy system to make it possible to store them.
energysystem.results['main'] = outputlib.processing.results(model)
energysystem.results['meta'] = outputlib.processing.meta_results(model)

# The default path is the '.oemof' folder in your $HOME directory.
# The default filename is 'es_dump.oemof'.
# You can omit the attributes (as None is the default value) for testing cases.
# You should use unique names/folders for valuable results to avoid
# overwriting.

# store energy system with results
energysystem.dump(dpath=None, filename=None) 

# ****************************************************************************
# ********** PART 2 - Processing the results *********************************
# ****************************************************************************

logging.info('**** The script can be divided into two parts here.')
logging.info('Restore the energy system and the results.')
energysystem = solph.EnergySystem()
energysystem.restore(dpath=None, filename=None)

# define an alias for shorter calls below (optional)
results = energysystem.results['main']
storage = energysystem.groups['storage']

# print a time slice of the state of charge
print('')
print('********* State of Charge (slice) *********')
print(results[(storage, None)]['sequences']['2020-08-25 08:00:00':
                                            '2020-08-26 15:00:00'])
print('')

# get all variables of a specific component/bus
custom_storage = outputlib.views.node(results, 'storage')
electricity_bus = outputlib.views.node(results, 'electricity')

# plot the time series (sequences) of a specific component/bus
if plt is not None:
    fig, ax = plt.subplots(figsize=(10,5))
    custom_storage['sequences'].plot(ax=ax, kind='line', drawstyle='steps-post')
    plt.legend(loc='upper center', prop={'size':8}, bbox_to_anchor=(0.5, 1.25), ncol=2)
    fig.subplots_adjust(top=0.8)
    plt.show()

    fig, ax = plt.subplots(figsize=(10,5))
    electricity_bus['sequences'].plot(ax=ax, kind='line', drawstyle='steps-post')
    plt.legend(loc='upper center', prop={'size':8}, bbox_to_anchor=(0.5, 1.3), ncol=2)
    fig.subplots_adjust(top=0.8)
    plt.show()

# print the solver results
print('********* Meta results *********')
pp.pprint(energysystem.results['meta'])
print('')

# print the sums of the flows around the electricity bus
print('********* Main results *********')
print(electricity_bus['sequences'].sum(axis=0))
```

**Comment by uvchik** [comment]
@leyetunji: I moved this issue to the oemof-solph repository because it seems to be a solph issue.

There are a few thing you can do to help us to help you.

1. Provide a minimal example. Remove all code parts that do not belong to the problem. Remove as many components as possible, so that the error still occur.

2. Provide information about the used version of oemof-solph and python

3. We need the whole error message to help, just `ValueError` is not enough.

Nevertheless, on a first glance the reason for the ValueError could be the wrongly defined CHP-component "peat". The `conversion_factor` should be defined in the `Transformer` and not in the `Flow`.

**Comment by leyetunji** [comment]
@uvchik thanks a lot for your reply. The version of the oemof solph is v0.2.x and the version of python in use here is python 3.7.

Firstly, how can I rearrange this code to capture the corrections you recommended
energysystem.add(solph.Transformer(
    label="peat",
    inputs={peat: solph.Flow()},
    outputs={bel: solph.Flow(nominal_value=10e10),
             bth: solph.Flow(nominal_value=10e10,variable_costs=50,
                             conversion_factors={bel: 0.58})}))

 Here are the error message I got;

  File "C:\Users\aadetunj\miniconda3\envs\oemofadeleye\lib\site-packages\oemof\groupings.py", line 173, in merge
    "Possibly duplicate uids/labels?")

ValueError: 
Grouping 
  2935027367368:peat
and
  2935027597768:peat
collides.
Possibly duplicate uids/labels?

Thanks for your help

**Comment by uvchik** [comment]
Code highlighting makes it easier to read the code. In this issues you can use the following structure. The preview button helps to see the result (I changed it in your postings above).
\`\`\`python
python code
\`\`\`

The error message says ```Possibly duplicate uids/labels?``` and that's what it is. Labels have to be unique but a Source has got the label "peat" and a Transformer, too.

To learn how to model a CHP-plant with the Transformer class please have a look at the [documentation](https://oemof-solph.readthedocs.io/en/v0.2.3/oemof_solph.html#transformer-basic).

The actual version of oemof solph is v0.4.1 you should consider to use the most actual version.

```
pip uninstall oemof
pip install oemof-solph
```

By the way, your GenericStorage is from v0.4.x you have to rename the parameter to use it with v0.2.x. In the documentation you can choose the version to be in line with the used version -> [Choose the right version](https://readthedocs.org/projects/oemof-solph/)

**Comment by leyetunji** [comment]
Thanks @uvchik
I implemented the changes in 

'''energysystem.add(solph.Transformer(
    label="peat",
    inputs={peat: solph.Flow()},
    outputs={bel: solph.Flow(nominal_value=10e10),
             bth: solph.Flow(nominal_value=10e10,variable_costs=50)},
    conversion_factors={bel: 0.58}))
'''

but I got a new error message:

'''  File "C:\Users\aadetunj\miniconda3\envs\oemofadeleye\lib\site-packages\oemof\outputlib\processing.py", line 17, in <module>
    from oemof.network import Node

ImportError: cannot import name 'Node' from 'oemof.network' (C:\Users\aadetunj\miniconda3\envs\oemofadeleye\lib\site-packages\oemof\network\__init__.py) 
'''
Please how do I run round this??

**Comment by uvchik** [comment]
You could reinstall all oemof packages (oemof-solph, oemof-network, oemof-tools) or you can use a clean virtual environment and install oemof-solph (the other packes are dependencies of oemof-solph).

Be aware that the default value of each conversion_factors is `1`(!). So you get an overall usage factor of 1.6 (160%) which is pretty magic :smirk:  `bel: 0.58` is the electrical efficiency (58%). You could add a thermal efficiency of 35% `bth: 0.35` to get an overall fuel usage of 93% (just an example :exclamation: )

```diff
- conversion_factors={bel: 0.58}))
+ conversion_factors={bel: 0.58, bth: 0.35}))
```

**Comment by leyetunji** [comment]
@uvchik this time I used another environment(pycharm) to run this but the situation is unchanged...
I also reinstalled all the packages.. and they all successfully installed.  

Here is the error message.

'''
 File "C:\Users\aadetunj\AppData\Local\Continuum\anaconda3\lib\site-packages\oemof\outputlib\processing.py", line 17, in <module>
    from oemof.network import Node
ImportError: cannot import name 'Node' from 'oemof.network' (C:\Users\aadetunj\AppData\Local\Continuum\anaconda3\lib\site-packages\oemof\network\__init__.py)
'''

**Comment by uvchik** [comment]
You have to use \`\`\` and not ''',  similar but not the same :-)

Pycharm is an IDE not an environment. With Anaconda you can create different [environments](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html) with different versions of python packages. A new environment is like a clean Python installation. Afterwards you can start to install oemof OR oemof-solph. Do NOT install the oemof package AND the oemof-solph package. The oemof package is deprecated. If you have both packages installed your error is very typical. There could also be orphan links of an old installation that cause this error, therefore it is helpful to use a fresh environment. With your IDE (e.g. Pycharm) you can decide which environment you want to use to run a script. Make sure it uses your new environment.

If you want to use an older version of oemof-solph (v0.2.x or v0.3.x) you have to install the meta package `oemof` with:

```
pip install oemof
```

If you want to install the most actual version (v0.4.x) you have to install oemof-solph:

```
pip install oemof-solph
```

Furthermore, you have to make sure, that you use the right example for yoru version. We improved the API a little bit and so only the v0.4.x examples work with v0.4.x and so on -> [Examples](https://github.com/oemof/oemof-examples/tree/master/oemof_examples/oemof.solph)

**Comment by leyetunji** [comment]
@uvchik I created a new environment and then decided to install oemof and oemof-solph; the following were the errors I got

```
ERROR: oemof 0.3.2 has requirement numpy<1.18,>=1.7.0, but you'll have numpy 1.18.1 which is incompatible.
ERROR: oemof 0.3.2 has requirement pyomo<5.7,>=4.4.0, but you'll have pyomo 5.7.1 which is incompatible.
```
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
oemof 0.3.2 requires pyomo<5.7,>=4.4.0, but you have pyomo 5.7.1 which is incompatible.
```
```
  File "C:\Users\aadetunj\Anaconda3\envs\clean\lib\site-packages\oemof\outputlib\processing.py", line 17, in <module>
    from oemof.network import Node

ImportError: cannot import name 'Node' from 'oemof.network' (C:\Users\aadetunj\Anaconda3\envs\clean\lib\site-packages\oemof\network\__init__.py)
````

**Comment by fwitte** [comment]
Hi @leyetunji,
as mentioned, you only need to install oemof-solph.

> Afterwards you can start to install oemof OR oemof-solph. Do NOT install the oemof package AND the oemof-solph package.

Best
Francesco

**Comment by jokochems** [comment]
I think, this can be closed since it is rather a usage topic than a software issue.
If there is still need for support, a new post could be made tin the opemod forum: https://forum.openmod.org/
